apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=
  host: ZGF0YWJhc2UtMS5jOXVzd3c2dWVjbmgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  port: MzMwNg==